version: '3'
services:
  #JENKINS
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    networks:
      - jenkins
  #POSTGRESS
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - jenkins
  #SONARQUBE
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
#services are connected to a bridge network
networks:
  jenkins:
    driver: bridge
#volume across services 
volumes:
  dbdata:
    driver: local